#!/usr/bin/env sh

. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

#Check Prettier
npm run check-format ||
{
  echo "Prettier check failed. Run npm run format, add changes and try commit again"
  false
}

#Check ESLint
npm run check-lint ||
{
  echo "ESLint check failed. Make the required changes listed above, add changes and try commit against"
  false
}

#Check tsconfig
{
  echo "Failed type check. Make the change require above, add changes and try commit against"
  false
}

// build
npm run build:watch ||
{
  echo "Your build failed. view the errors above"
  false
}
